[package]
name = "tetrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figlet-rs = "0.1.3"
crossterm = "0.23.2"
fastrand = "1.7.0"
